### ISSUE TITLE
Notice: Undefined property: stdClass::$duration in blocks/opencast/index.php 

### ISSUE THREAD

**Issue by loewis** [unirz-tu-ilmenau/moodle-block_opencast#128] opened 2020-04-22 09:36 UTC
When I upload a video through Opencast Studio, I get the error message in the title, from the code fragment
```
        if ($video->duration) {
            $row[] = userdate(strtotime($video->start) + intdiv($video->duration, 1000),
                get_string('strftimedatetime', 'langconfig'));
        } else {
```

The problem is that for these videos, duration is not set at all. That may be a bug in Opencast Studio as well, but it would be better of the block would cope with that missing property.

**Comment by tobiasreischmann** [comment] 2020-04-22 12:50
Yes, I have recognized this issue also.
However, for now just a warning is printed if you have debugging on.
Otherwise, this problem causes no harm.

Feel free to provide a patch, nevertheless. :)

**Comment by abias** [comment] 2020-04-29 10:02
Not really a solution to this issue, but a note: In #131, I submitted a patch to hide the duration column completely. If the column is not shown at all, then you don't get the debug notice ;)

**Comment by tobiasreischmann** [comment] 2020-06-26 15:28
The issue is fixed in the newest version

**Closed by tobiasreischmann** 2020-06-26 15:28 UTC
